### ISSUE TITLE
Release archiveweb.page with wacz-uploader and auto-js-ipfs support

### ISSUE THREAD

**Issue by RangerMauve** [webrecorder/archiveweb.page#113]
The IPFS uploading in archiveweb.page can be handled by using wacz-uploader

**Comment by ikreymer** [comment]
Instead of wacz-uploader, I think it will probably be simpler to convert the `addAll()` to instead generate a car stream.
Started on this with an in-memory repo, but actually would likely be simpler to just use this new unixfs library:
https://github.com/ipld/js-unixfs
and convert this to use the api: https://github.com/webrecorder/archiveweb.page/blob/auto-js-ipfs/src/ext/ipfsutils.js#L26
which provides a way to stream multiple files to a car.

**Comment by RangerMauve** [comment]
Currently blocked on fixing w3s.link gateway issues. https://github.com/RangerMauve/auto-js-ipfs/issues/9

Might be stuck on that though so I'll start looking into this.

**Comment by RangerMauve** [comment]
This is also pending on us figuring out pinning https://github.com/RangerMauve/auto-js-ipfs/issues/5

**Comment by ikreymer** [comment]
> Currently blocked on fixing w3s.link gateway issues. [RangerMauve/auto-js-ipfs#9](https://github.com/RangerMauve/auto-js-ipfs/issues/9)
> 

If we don't extend a template, then this shouldn't be an issue, right? We just do a CAR upload of 4 files.

**Comment by RangerMauve** [comment]
@ikreymer got an initial version for this in #119 

Some next steps will be to get streaming working and to split up the CAR files.

**Comment by ikreymer** [comment]
Released in 0.9.x!
