### ISSUE TITLE
The wikipedia mirror website replay erro

### ISSUE THREAD

**Issue by Mingmingshuai** [webrecorder/archiveweb.page#123]
As you can see , the recording process is right.
![image](https://user-images.githubusercontent.com/76103984/207004884-6ce5577b-5b51-46a9-9757-7696302c826d.png)

After Saving the website of the wikipwdia mirror,  the replaywebsite exe and online review website both can't show the site , there is only blank interface, showing the loading status。
![image](https://user-images.githubusercontent.com/76103984/207004634-34208572-a60b-4da0-adce-58b10e30b593.png)

**Comment by ikreymer** [comment]
@Mingmingshuai can you provide a sample WACZ file for testing?
The recording works with live Wikipedia itself and I do not have access to that mirror to test.

**Comment by Mingmingshuai** [comment]
Thanks for your response, the site address is : https://en.wikipedia.wmmirror.live/wiki/Main_Page. 
Here is the WACZ file.
[Cryocooler-wiki.zip](https://github.com/webrecorder/archiveweb.page/files/10234476/Cryocooler-wiki.zip)

**Comment by ikreymer** [comment]
Thanks, it seems like this mirror has a check where it attempts to check `localStorage.getItem()` and if an object isn't set, it sets it with `localStorage.setItem()` and then calls `window.location.reload()`. Since this is an archive, its not persisting local storage, so this causes an infinite reload loop. To avoid, this probably best solution is just to disable `window.location.reload()` altogether, as it likely only leads to negative behavior in an archive, since there should be no persistent state...

This will be fixed in an updated version of replayweb.page / archiveweb.page soon. The above archive does work in replayweb.page with the updated wombat.js

**Comment by ikreymer** [comment]
Replay issue, fixed in replayweb.page 1.7.9, will be in next release of archiveweb.page

**Comment by Mingmingshuai** [comment]
Thanks for your kindly solution.

**Comment by ikreymer** [comment]
Fixed in 0.9.4 as well.
