### ISSUE TITLE
Switch to Manifest V3

### ISSUE THREAD

**Issue by steph-nb** [webrecorder/archiveweb.page#131]
What about switching to manifest V3?
See:
https://developer.chrome.com/docs/extensions/mv3/intro/

As of January 17, 2022 the Chrome Web Store has stopped accepting new Manifest V2 extensions. We strongly recommend migrating your extensions to Manifest V3 as soon as possible; this will become mandatory after [Manifest V2 is phased out](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/) in 2024.

**Comment by ikreymer** [comment]
Yes, this is planned, eventually. I've done some tests and mostly it works, since already using a service worker.
There are some questions that remain regarding the debugger being attached (https://bugs.chromium.org/p/chromium/issues/detail?id=1139096&q=chrome.debugger%20manifest%20v3&can=2) and the CSP policy (which is currently bypassed for replay)

**Comment by tsemachh** [comment]
Hi @ikreymer 
We try not to push our extension to the chrome store and it does require Manifest 3 only (New extension)
Want to share few obstacles we are facing regarding usage of eval in the code:
1. One of the libraries used by WebRecorder is protobufjs there's issue opened there I also asked it to be promoted:
[https://github.com/protobufjs/protobuf.js/issues/1754 ](https://github.com/protobufjs/protobuf.js/issues/1754 )- It's being handled there , there's a PR it's not merged yet

2.  In the original recorder there's a code with eval which loads the pdf.js  library:
_src/extractPDF.js_
const res = await fetch(new URL("pdf/pdf.min.js", baseUrl).href);\n    eval(await res.text())
From some reason(lazy load) it loads it using eval , it can be changed to be loaded using import.
(Even though it's not really a security issue since it loads only local file)

Will update if we face more issue as I said we are in the process now

**Comment by tsemachh** [comment]
Note the protobuf is consumed from IPFS Utils which uses @ipld/unixfs and there's also an issue for it:
[https://github.com/ipld/js-unixfs/issues/31](https://github.com/ipld/js-unixfs/issues/31)
Seems like everyone are trying to get rid of it , but it ain't going no where
Will update if I see progress

**Comment by ikreymer** [comment]
> Hi @ikreymer We try now to push our extension to the chrome store and it does require Manifest 3 only (New extension) Want to share few obstacles we are facing regarding usage of eval in the code:

To clarify, are these errors you're encountering in the extension, or comments from the chrome web store submission process?

The MV3 branch does build and run, though haven't tested it as extensively yet, and only in dev builds.

Can you put the fork that you're using up on GitHub somewhere, so we can be more clear what you're referring to?

**Comment by tsemachh** [comment]
The errors are in the submission process, will share and let you know ASAP

**Comment by AntiMoron** [comment]
hey, support me: 
https://github.com/protobufjs/protobuf.js/pull/1941

**Comment by ikreymer** [comment]
This is generally working, except for the protobuf issue ipld/js-unixfs#31. As a temporary solution, so we can migrate, may need to drop IPFS serialization on first MV3 release.

**Comment by tsemachh** [comment]
We finally got it approved but with the changes I mentioned before aka next patches:
[https://github.com/shefing/web_recorder_ext_public/tree/main/patches](https://github.com/shefing/web_recorder_ext_public/tree/main/patches)

Not sure if approval for existing extension will be easier than new extensions.

I will check with Riki who manages the project if she encountered other issues.
(Unless she gave birth , it should be any day now)
