### ISSUE TITLE
About the preservation of dynamic websites

### ISSUE THREAD

**Issue by SheriffRabbit** [webrecorder/archiveweb.page#177]
<img width="393" alt="image" src="https://github.com/webrecorder/archiveweb.page-site/assets/86582915/edddd4de-f8fb-4bd5-b589-145f285ecc95">
Hello, when I was using the plug-in to record, I found that when I clicked to start recording, there would be an error that the dynamic rendering website could not be recorded. May I ask what I need to do to save it

**Comment by ikreymer** [comment]
This is most likely caused by another extension interfering. Due to security settings in Chromium, an extension can't access data from another extension. Try disabling all other extensions when using ArchiveWeb.page, or create a new profile with only ArchiveWeb.page installed. That should solve this issue.

**Comment by SheriffRabbit** [comment]
Thank you for your answer
