### ISSUE TITLE
How to add new session to existing collection

### ISSUE THREAD

**Issue by clausjuhl** [webrecorder/archiveweb.page#18]
Hi.
I've previously been using the Webrecorder and Webrecorder Player to record and replay webcollections on my Mac (Big Sur), but WebRecorder stopped working on my Mac, and I discovered that you had been busy :) I have a couple of collections that I add sessions to from time to time, but how is it possible to add sessions to existing collections (local WARC-files) with ArchiveWeb.page.app (desktop-version)? Am I missing something? Thanks! /Claus

**Comment by ikreymer** [comment]
No, you're not missing anything. This is a feature that is currently in progress, importing existing collections.. Will definitely update when this is available!

**Comment by clausjuhl** [comment]
Hi Ilya. Ok. Thank you. And until then, should I just start a new collection, and then merge the warc-files later?

**Comment by jakewarren** [comment]
Just chiming in that #51 implements this feature and works great for me. Thanks so much for implementing this @ikreymer!

**Comment by ikreymer** [comment]
Thanks for testing, this is indeed now implemented! There is an import button that allows you to add to either a new or existing collection. The import fully reads a WARC or WACZ file into the extension/app data store.
Will be updating the guide too soon! Let us know if you run into any issues.

**Comment by MattSuda** [comment]
The import file to existing collection feature is not working for me. I just get weird characters loaded instead of the actual website content. Happens in Chrome extension and downloaded app on macOS.

However, if I import the file and create a new collection, then the website content loads fine. I couldn't find this issue reported anywhere yet.

![importnotworking](https://user-images.githubusercontent.com/28849313/150883375-d862b26b-3f45-4753-8377-67e73807e42f.png)
