### ISSUE TITLE
This page downloads 1.4 GB of data, only when recording

### ISSUE THREAD

**Issue by ZheniaZuser** [webrecorder/archiveweb.page#182]
https://syntystore.com/products/polygon-sci-fi-cyber-city
Even if Youtube is blocked with uBlock origin, this still happens
Looking at network activity, it doesnt seem to happen when viewing the page without recording.

**Comment by ikreymer** [comment]
With 0.11.3, this will not happen by default. This was happening because the autofetch behaviors load every resolution of every image on the page, and this page has a lot of images at multiple resolutions! 
Previously, the behavior would start immediately on page load, now it only starts if Autopilot start is clicked, so without that, the additional resolutions will not be loaded.
