### ISSUE TITLE
Desktop App doesn't work on Windows 8

### ISSUE THREAD

**Issue by VetaLioSTV** [webrecorder/archiveweb.page#200]
As title say's, unfortunately Desktop App not working on Windows 8 OS, but in fact extension runs properly in older version of Chrome which is latest available for Windows 7 / 8.

Any ideas / restrictions on such OS?

**Comment by ikreymer** [comment]
Unfortunately, I don't think there's much we can do, since Electron no longer supports these versions of Windows: https://www.electronjs.org/blog/electron-23-0#dropping-windows-7881-support
The latest supported version of Electron is 28 now, I believe. We don't currently have the resources to provide support for earlier versions, I would recommend using the extension instead.
