### ISSUE TITLE
Not copying the svg embedded as an object

### ISSUE THREAD

**Issue by manikantag** [webrecorder/archiveweb.page#201]
Thanks for the excellent tools... better than any other tool I have test for so long... 👏

I'm facing an issue with copying svg files embedded using `object` tag (not sure if this is svg+object specific). For example, the below image in the page is not part of recorded page.

Test link: https://www.educative.io/courses/grokking-modern-system-design-interview-for-engineers-managers/how-the-domain-name-system-works

### Expected:
![image](https://github.com/webrecorder/archiveweb.page/assets/317299/1ed4c518-fb34-420d-bca7-881c6de0c1cf)

DOM:
![image](https://github.com/webrecorder/archiveweb.page/assets/317299/cf310d4e-969c-48e3-983a-4de9eb15948e)

### Actual:

![image](https://github.com/webrecorder/archiveweb.page/assets/317299/84b1154d-d265-49b6-936a-77a3faadf768)

DOM: 
![image](https://github.com/webrecorder/archiveweb.page/assets/317299/65bbffad-d611-425e-a31b-e5f738d15aa6)

What could be the issue? is there a workaround? Thanks

**Comment by manikantag** [comment]
Using Chrome extension v0.11.3 on Windows 11 Home

**Comment by ikreymer** [comment]
This is due to the two issues: one is <object> tags aren't properly handled by service workers, but luckily SVGs in objects can just be converted to <img> tags. This will be fixed in wabac.js and wombat.js
Another issue is the ruffle injection on the page was interfering with the page itself, which prevents the above fix from being as simple. Will have some kind of fix for this soon.

**Comment by ikreymer** [comment]
This should be fixed in ReplayWeb.page 2.0.1 and upcoming 0.12.1 release.
