### ISSUE TITLE
[Bug]: Extremely slow import of wacz file (in Brave extension)

### ISSUE THREAD

**Issue by ZheniaZuser** [webrecorder/archiveweb.page#212]
### ArchiveWeb.page Version

v0.11.3

### What did you expect to happen? What happened instead?

Trying to import .wacz file that was created there a few days ago.
Note: File chooser is invisible in recording
https://youtu.be/ZyHv1rIsTTw

### Step-by-step reproduction instructions

Try to import this file: https://drive.google.com/file/d/1RfUxe1SGSVkkFGQm1uX-_TlwTRi7epp8/view?usp=drive_link

### Additional details

This file was created there a few days ago by me

**Comment by ikreymer** [comment]
How slow was it importing? I just tried with latest build of 0.12.0 and it imported in <1 min - it looks like the WACZ has a lot of small files in it. The import speed has less to do with total size, but with number of archived URLs in the archive.

**Comment by ikreymer** [comment]
Ah, just tested in Brave, and do indeed see that it is slow as well - seems to only happen in Brave, tested Chrome, Chrome Beta and Canary (Chrome 125, 126, 127) and seems to be uploading fine there...

**Comment by ikreymer** [comment]
I found the source of the issue, it is because Brave disable the native file system api by default, which the extension assumed was available in Chromium-based browsers: brave/brave-browser#18979
(Without it, I think it ends up loading the whole object into memory, instead of streaming, which is something to be fixed separately).

But the good news, is that you can enable it if you go to `brave://flags` and search for `File System Access API` and then reload Brave. Uploading should now work just as fast as in Chrome.

Will close this for now as that resolves the immediate issue.
