### ISSUE TITLE
Is it possible to download web archives as WARC files instead of WACZ?

### ISSUE THREAD

**Issue by YousufSSyed** [webrecorder/archiveweb.page#49]
Either warc or warc.gz?

**Comment by ikreymer** [comment]
Yes,  from the individual archive view, on the left, you can download either WACZ or WARC:
<img width="439" alt="Screen Shot 2021-08-29 at 11 43 55 AM" src="https://user-images.githubusercontent.com/1015759/131261837-a5666348-3ceb-4270-b24a-d9aaceeb25dd.png">

Note that the WACZ is just a zip file that contains WARC as well. We recommend WACZ as it includes additional metadata, such as list of pages and a build-in index, and that makes it easy to host large web archives online and make them accessible without download the entire file. With WARC, the entire file needs to be downloaded as there is no built-in index (due to limitation of the WARC standard).
