### ISSUE TITLE
Importing archive file to an existing collection doesn't import correctly

### ISSUE THREAD

**Issue by MattSuda** [webrecorder/archiveweb.page#62]
The import archive file to **existing collection** feature is not working for me. I just get weird characters loaded instead of the actual website content. Happens in Chrome extension and downloaded app on macOS.

However, if I import the archive file and **create a new collection**, then the website content loads fine. I couldn't find this issue reported anywhere yet.

This is an imported archive file (.warc) from Conifer. Same thing happens with multiple different archive files for different websites.

App v0.7.4

![importnotworking](https://user-images.githubusercontent.com/28849313/150883375-d862b26b-3f45-4753-8377-67e73807e42f.png)

_Originally posted by @MattSuda in https://github.com/webrecorder/archiveweb.page/issues/18#issuecomment-1020661600_

**Comment by jakewarren** [comment]
I am able to replicate on v0.7.6 with a WARC downloaded from Conifer. I don't think it's an issue on Conifer's side because the WARC replays just fine via https://replayweb.page/. 

If I export a WARC 1.1/1.0 file from archiveweb.page and then try to import into another collection it does import and replay but curiously the "page" isn't detected so I have to hunt down the URL to view it. With the Conifer WARC the "page" is detected and displayed under the Pages tab it just doesn't display correctly.

Probably a separate issue but I can't get HAR import (with HAR exported from Chrome 97) to work with either archiveweb.page or replayweb.page.

**Comment by ikreymer** [comment]
Thanks for opening a new issue, will investigate, hopefully a quick fix.

**Comment by ikreymer** [comment]
Hm, I haven't been able to repro this - definitely appears to be an encoding issue, but maybe particular to something page.
Can anyone share a WARC or WACZ file that demonstrates this issue?

**Comment by MattSuda** [comment]
You can download this test collection I made here with several different websites:

https://app.box.com/s/ru8ecl2tln8kr6ex5yzhxt6504hqghh5

**Comment by ikreymer** [comment]
The issue was that content-encoding is disabled by default in archiveweb.page native collections (since the data is never compressed), however, when importing external WARC/WACZ that were not created in archiveweb.page, there will likely be compressed data, so must reenable it.
(Better solution is to remove this option altogether, but that's for another refactor)

Should be fixed in 0.7.7 release.

**Comment by jakewarren** [comment]
0.7.7 resolved the issue for me. thanks!

**Comment by MattSuda** [comment]
Works in 0.7.7 for me as well! Thanks! 🙂

**Comment by MattSuda** [comment]
Tested and it looks fixed for me as well in 0.7.7 🙂
